[package]
name = "trashy"
version = "0.1.0"
edition = "2021"
description = "Plans, prompts, and executes a cleanse of your trashy filesystem(s)"
license = "MIT"
repository = "https://github.com/nickheyer/trashy"

[dependencies]
anyhow = "1"
blake3 = "1"
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
dirs = "6"
globset = "0.4"
libc = "0.2"
ratatui = "0.29"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
trash = "5"
unicode-width = "0.2"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
